name: CI

on:
  push:
    branches:
    - main
    - release/*
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - 'docs/**'
    
jobs:
  build:

    runs-on: windows-2022
    
    steps:
    - name: Clone Toolkit
      uses: actions/checkout@v1
    
    - name: Setup Visual Studio Command Prompt
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Install MAUI Workload
      run: |
        dotnet workload install maui@9.0.100
        dotnet workload restore src/Toolkit/Toolkit.Maui/Esri.ArcGISRuntime.Toolkit.Maui.csproj --from-previous-sdk
       
    - name: Build
      run: |
        msbuild /restore /t:Build src/Esri.ArcGISRuntime.Toolkit.sln /p:Configuration=Release
#       msbuild /restore /t:Build src/Esri.ArcGISRuntime.ARToolkit.sln /p:Configuration=Release
      
    - name: Upload artfacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Packages
        path: Output/NuGet/Release

    - name: Publish to Esri Nuget Repo
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        dotnet nuget push Output\NuGet\Release\*.nupkg --api-key  ${{ secrets.GithubPushPackagesSecret }} --source https://nuget.pkg.github.com/esri/index.json 
